apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service-deploy
  labels:
    app: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
      - name: student-service
        image: docker.io/rohaanoa/student_service:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dockerhub-credential
      
