apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: student-service-service
  name: student-service-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    name: http
  selector:
    io.kompose.service: student-service
